fix(shortcuts): fixes #252
Link to `...-script.py` instead of `....exe` to prevent the following
error when launching MicroDrop from the Windows Start Menu shortcut:

    SyntaxError: Non-ASCII character '\x90' in file C:/Users/chris/MicroDrop2/Scripts\microdrop-profile-manager.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Note: the error is not actually displayed, since the window closes
immediately after the exception occurs.**