fix(build): bump microdrop-plugin-template version
Bump required package to `microdrop-plugin-template>=1.3` to prevent the
following error during `paver build_installer` command:

    Error: File 'Lib/site-packages/git/test/fixtures/diff_i' found in multiple packages: microdrop-plugin-template-1.1.post30-0.tar.bz2, gitpython-2.1.3-py27_0.tar.bz2